### PR TITLE
csproj props tidy

### PR DESCRIPTION
**Pull request by rkm**
## Proposed Changes

Tidy common csproj options into `Directory.Build.props` files for all, src, and test projects

## Types of changes

What types of changes does your code introduce? Tick all that apply.

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New Feature (non-breaking change which adds functionality)
- [ ] Breaking Change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation-Only Update (if none of the other choices apply)
  - In this case, ensure that the message of the head commit from the source branch is prefixed with `[skip ci]`

## Checklist

By opening this PR, I confirm that I have:

- [x] Reviewed the [contributing](https://github.com/SMI/SmiServices/blob/master/CONTRIBUTING.md) guidelines for this repository
- [x] Ensured that the PR branch is in sync with the target branch (i.e. it is automatically merge-able)
- [ ] Updated any relevant API documentation
- [ ] Created or updated any tests if relevant
- [x] Accurately updated the [CHANGELOG](https://github.com/SMI/SmiServices/blob/master/CHANGELOG.md)
  - NOTE: This ***must*** include any changes to any of the following files: default.yaml, any of the RabbitMQ server configurations, GlobalOptions.cs
- [x] Listed myself in the [CONTRIBUTORS](https://github.com/SMI/SmiServices/blob/master/CONTRIBUTORS.md) file 🚀
- [x] Requested a review by one of the repository maintainers

## Issues
-

### CODE REVIEW

**Comment by rkm** [comment]
Dependabot apparently supports updating packages in `Directory.Build.props` files, but we should check back on this to make sure

**Review by tznind — APPROVED** [review]

**Comment by tznind** [comment]
I fixed the xml comments and the easy warnings just 3 about `ISubscription` being obsolete and some sketchy unreachable code in DeadLetterQueue related stuff.

**Comment by rkm** [comment]
Not sure about that AppVeyor branch failure. Seems to be unrelated since the PR build is passing?

**Comment by tznind** [comment]
Yeah thats a little strange... not sure but doesn't seem to be related to this PR so go ahead and merge I'd say.

**Comment by jas88** [comment]
> Not sure about that AppVeyor branch failure. Seems to be unrelated since the PR build is passing?

The PR "build" _always_ passes - it doesn't have access to the Coveralls token anyway, so can't do anything useful except delay the actual build half an hour each time.

I retried and got some file not found errors on csproj files from the Nuspeciscorrect tests, which don't fail on my machine. Appveyor glitching?

**Pull request merged**
