### PR TITLE
Add note to ping mattermost on releases

### PR DESCRIPTION
**Pull request by rkm**
## Proposed Changes

Small note for future releases.

## Types of changes

What types of changes does your code introduce? Tick all that apply.

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New Feature (non-breaking change which adds functionality)
- [ ] Breaking Change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation-Only Update (if none of the other choices apply)
  - In this case, ensure that the message of the head commit from the source branch is prefixed with `[skip ci]`

## Checklist

By opening this PR, I confirm that I have:

- [x] Reviewed the [contributing](https://github.com/SMI/SmiServices/blob/master/CONTRIBUTING.md) guidelines for this repository
- [x] Ensured that the PR branch is in sync with the target branch (i.e. it is automatically merge-able)
- [ ] Updated any relevant API documentation
- [ ] Created or updated any tests if relevant
- [x] Created a [news](https://github.com/SMI/SmiServices/blob/master/news/README.md) file
    -   NOTE: This ***must*** include any changes to any of the following files: default.yaml, any of the RabbitMQ server configurations, GlobalOptions.cs
- [x] Listed myself in the [CONTRIBUTORS](https://github.com/SMI/SmiServices/blob/master/CONTRIBUTORS.md) file 🚀
- [x] Requested a review by one of the repository maintainers

## Issues
-

### CODE REVIEW

**Review by howff — APPROVED** [review]
I thought this was going to be a github action to automatically send a message to mattermost ;-)

**Comment by rkm** [comment]
You know, I think we did have a bot set-up at some point to ping mattermost. Any thoughts @2bPro ?

**Comment by 2bPro** [comment]
> You know, I think we did have a bot set-up at some point to ping mattermost. Any thoughts @2bPro ?

That was the initial plan and we did indeed set up a Mattermost bot successfully, the problem was allowing Grafana to send messages to it from inside the SH. After asking systems, they recommended I would set up Outlook rather than Mattermost notifications (maybe for security reasons). If the team really wants this, I can chase it up again with systems and see if they changed their mind.

**Comment by rkm** [comment]
I think this is a bit easier - getting the bot to notice GitHub releases and sending a message to the channel?

**Comment by jas88** [comment]
> I think this is a bit easier - getting the bot to notice GitHub releases and sending a message to the channel?

There's a ready-made Github Action for notifying Mattermost - no bot needed as long as EPCC Mattermost will accept the notification: https://github.com/marketplace/actions/mattermost

**Pull request merged**
