### PR TITLE
Release 1.0.0

### PR DESCRIPTION
**Pull request by rkm**
This is the first stable release after importing the repository from the private [SMIPlugin](https://github.com/HicServices/SMIPlugin) repo.

### CODE REVIEW

**Comment by rkm** [comment]
Checks failed here https://travis-ci.org/SMI/SmiServices/jobs/612548452#L3003

**Comment by tznind** [comment]
Interesting `GeneratedInstanceUID-122095` wonder if there is a non constant seed somewhere.  Or a reuse of a mapping table between tests... a problem for Monday.

**Comment by rkm** [comment]
This build passed where I only ran the DicomRelationalMapper tests: https://travis-ci.org/SMI/SmiServices/jobs/612538057

**Comment by rkm** [comment]
Looks good, feel free to merge!

**Pull request merged**
