### PR TITLE
Feature/is identifiable as a service

### PR DESCRIPTION
**Pull request by tznind**
## Proposed Changes

Summarise your changes, and include a link to the [CHANGELOG](https://github.com/SMI/SmiServices/blob/master/CHANGELOG.md) diff.

## Types of changes

What types of changes does your code introduce? Tick all that apply.

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New Feature (non-breaking change which adds functionality)
- [ ] Breaking Change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation-Only Update (if none of the other choices apply)
  - In this case, ensure that the message of the head commit from the source branch is prefixed with `[skip ci]`

## Checklist

By opening this PR, I confirm that I have:

- [x] Reviewed the [contributing](https://github.com/SMI/SmiServices/blob/master/CONTRIBUTING.md) guidelines for this repository
- [x] Ensured that the PR branch is in sync with the target branch (i.e. it is automatically merge-able)
- [x] Updated any relevant API documentation
- [x] Created or updated any tests if relevant
- [x] Accurately updated the [CHANGELOG](https://github.com/SMI/SmiServices/blob/master/CHANGELOG.md)
  - NOTE: This ***must*** include any changes to any of the following files: default.yaml, any of the RabbitMQ server configurations, GlobalOptions.cs
- [x] Listed myself in the [CONTRIBUTORS](https://github.com/SMI/SmiServices/blob/master/CONTRIBUTORS.md) file 🚀
- [x] Requested a review by one of the repository maintainers

## Issues

If relevant, tag any issues that are *expected* to be resolved with this PR. E.g.:

- Closes #\<issue-number>
- ...

### CODE REVIEW

**Comment by tznind** [comment]
Seem to be facing this issue in travis : https://github.com/charlesw/tesseract/issues/503

**Comment by rkm** [comment]
Do you have a local ubuntu VM to test on? I can spend some time debugging this now if you like?

**Comment by howff** [comment]
A note of caution about including pre-compiled libraries - if you compile on ubuntu in order to get travis working then it won't work inside the safe haven which is centos.

**Comment by rkm** [comment]
So I think there are 2 options here:
- Setup Travis to build & run the tests in a CentOS Docker container
- Wait until we have the full test environment in Azure and build any specific required libs there

**Comment by tznind** [comment]
James and I are doing a bit of investigating.  He has a CentOS 7 box here so should understand more about the issue / compatibility soon.

**Pull request merged**
