### PR TITLE
Rules base manager

### LINKED ISSUE #753: Rulesbase manager for IsIdentifiable
We have a growing number of rules in IsIdentifiableReviewer (~10,000) .  All most are based on regular expressions.  Some of these rules should feed back into the main IsIdentifiable tool.

We need a console gui tool to visualise these rules and do some automatic transfering of rules upstream to the main IsIdentifiable tool.

We also need this to simplify rules like `^bob bob$` into simple string rules for inclusion in the verbatim patterns rule style.

### PR DESCRIPTION
**Pull request by tznind**
## Proposed Changes

Adds 'Rules View' tab to the IsIdentifiableReviewer 

image
_All data in this screenshot is synthetic_

I have marked this as a Breaking Change because editing rules will re-write the yaml of the rules which has the side effect of removing all whitespace and comments.  Since these files were previously hand edited any notes people have added will be removed.

But I think having these programatically editable is going to be required going forwards e.g. for moving new rules out of reviewer and up to the 'analyser' (IsIdentifiable).

This is a first pass for viewing and deleting dodgy rules.  In future we can expand it to move commands around between the files and edit them etc.

**Note:** In order for the 'analyser' rules to appear in the tree view the appropriate settings should be configured in `default.yaml` settings file (see https://github.com/SMI/SmiServices/pull/795)

## Types of changes

What types of changes does your code introduce? Tick all that apply.

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New Feature (non-breaking change which adds functionality)
- [x] Breaking Change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation-Only Update (if none of the other choices apply)
  - In this case, ensure that the message of the head commit from the source branch is prefixed with `[skip ci]`

## Checklist

By opening this PR, I confirm that I have:

- [x] Reviewed the [contributing](https://github.com/SMI/SmiServices/blob/master/CONTRIBUTING.md) guidelines for this repository
- [x] Ensured that the PR branch is in sync with the target branch (i.e. it is automatically merge-able)
- [ ] Updated any relevant API documentation
- [x] Created or updated any tests if relevant
- [x] Created a [news](https://github.com/SMI/SmiServices/blob/master/news/README.md) file
    -   NOTE: This ***must*** include any changes to any of the following files: default.yaml, any of the RabbitMQ server configurations, GlobalOptions.cs
- [x] Listed myself in the [CONTRIBUTORS](https://github.com/SMI/SmiServices/blob/master/CONTRIBUTORS.md) file 🚀
- [x] Requested a review by one of the repository maintainers

## Issues

If relevant, tag any issues that are *expected* to be resolved with this PR. E.g.:

- Closes #753 
- ...

### CODE REVIEW

**Review by howff — APPROVED** [review]
The IsIdentifiableReivewer is quite a significant tool now. Is there a full user manual in this repo or in the azure docs repo?

**Comment by tznind** [comment]
> 
> 
> The IsIdentifiableReivewer is quite a significant tool now. Is there a full user manual in this repo or in the azure docs repo?

Not yet but I agree its a priority, I can create an issue or do you want this handled in this PR before merging?

**Comment by howff** [comment]
I don't mind, whatever's easiest for you.

**Comment by tznind** [comment]
Ok I've created an issue https://github.com/SMI/SmiServices/issues/820 and will tackle it when I have some time as my next priority :)

**Pull request merged**
