### PR TITLE
manually update csvhelper to 25.0.0, fo-dicom to 4.0.7

### PR DESCRIPTION
**Pull request by rkm**
## Types of changes

What types of changes does your code introduce? Tick all that apply.

- [x] Bugfix (non-breaking change which fixes an issue)
- [x] New Feature (non-breaking change which adds functionality)
- [ ] Breaking Change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation-Only Update (if none of the other choices apply)
  - In this case, ensure that the message of the head commit from the source branch is prefixed with `[skip ci]`

## Checklist

By opening this PR, I confirm that I have:

- [x] Reviewed the [contributing](https://github.com/SMI/SmiServices/blob/master/CONTRIBUTING.md) guidelines for this repository
- [x] Ensured that the PR branch is in sync with the target branch (i.e. it is automatically merge-able)
- [x] Updated any relevant API documentation
- [x] Created or updated any tests if relevant
- [ ] Accurately updated the [CHANGELOG](https://github.com/SMI/SmiServices/blob/master/CHANGELOG.md)
  - NOTE: This ***must*** include any changes to any of the following files: default.yaml, any of the RabbitMQ server configurations, GlobalOptions.cs
- [x] Listed myself in the [CONTRIBUTORS](https://github.com/SMI/SmiServices/blob/master/CONTRIBUTORS.md) file 🚀
- [x] Requested a review by one of the repository maintainers

## Issues
-

### CODE REVIEW

**Comment by rkm** [comment]
Remaining failures caused by upstream BadMedicine DICOM lib

**Comment by rkm** [comment]
Need to bump this to 24.0.1

**Comment by rkm** [comment]
@jas88 I think we also need a release of BadMedicine.Dicom to bring-in the API updates

**Comment by jas88** [comment]
> @jas88 I think we also need a release of BadMedicine.Dicom to bring-in the API updates

Good point - https://github.com/HicServices/BadMedicine.Dicom/pull/38 in the queue now

**Review by jas88 — APPROVED** [review]

**Pull request merged**
